<?php
/**
*@file
*List Content by Type.
*/
/**
* Implementation of hook_menu().
*/
function lll_menu() {
    $items['lll'] = array(
        'title' => 'List Content by Type',
        'description' => 'Access content by type',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('lll_list_content'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['lll_list'] = array(
        'title' => 'Content Listing',
        'description' => 'Show content list',
        'page callback' => 'lll_content_report',
        'access arguments' => array('administer site configuration'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}
/*
* Build Form
*/
function lll_list_content() {
    $options = node_get_types('names');
    $form['lll_node_type'] = array(
        '#type' => 'select',
        '#title' => t('You can select content type to list'),
        '#options' => $options,
        '#default_value' => variable_get('lll_node_type', array('rental')),
        '#description' => t('Items from the selected content types will be listed.'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('List'),
        '#submit' => 'lll_content_report',
    );
    return $form;
}
function lll_list_content_validate($form,$form_state) {
}
function lll_list_content_submit($form,$form_state) {
    $type= $form_state['values']['lll_node_type'];
    $form['#redirect'] = array('lll_list', "type=$type");
}
function lll_content_report() {
    $type= $_GET['type'];
    $output = '';
    $result = db_query("SELECT nid, title FROM {node} WHERE type = '%s' ORDER by title, created DESC", $type);
    while ($row = db_fetch_array($result)) {
           $output .= l($row['title'], 'node/' . $row['nid']); }
    $output .= l('Return to select content type', 'lll');
    return $output;
}