<?php
// $Id: theme.inc,v 1.1 2009/09/30 20:47:02 neclimdul Exp $
/**
 * @file
 * Theme related functions.
 *
 * This file exists to deal with views. It expects a file to exist for your
 * preprocess functions. The problem is, core's theme system isn't very good
 * about consistently including this file. So, if you absolutely must have your
 * preprocess run, you need to have it in your module. That's why this file is
 * also empty.
 */
